### ISSUE TITLE
importing modules inside of ESM package fails

### ISSUE THREAD

**Issue by ksmithut** [panva/jose#104]
**Describe the bug**

Importing a module from this package inside of an ESM enabled package results in an Error.

**To Reproduce**

I have a gist here: https://gist.github.com/ksmithut/d5f787fa0eca67295c5d360054fccf82

- macOS 11.0.1
- node 15.2.0

You can clone it and run it:

```js
git clone https://gist.github.com/ksmithut/d5f787fa0eca67295c5d360054fccf82 reproduce
cd reproduce
npm install
npm start
```

Code to reproduce the behaviour:

```json
{
  "type": "module",
  "dependencies": {
    "jose": "^3.0.1"
  }
}
```

```js
import generateKeyPair from 'jose/util/generate_key_pair'
```

**Expected behaviour**

To import the module in an ESM environment.

**Environment:**

- `jose` version: v3.0.1
- affected runtime is: Node.js 15.2.0 and Node.js 14.15.0 tested

**Additional context**

Perhaps if the ESM module files were exported with a `.mjs` extension it would work as expected? I'm not sure what the right answer is for modules exporting both CJS and ESM.

- [x] the bug is happening on latest `jose` too.
- [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
sigh, the individual package.json entries in each of the submodules didn't get published ... looking into it.

**Comment by panva** [comment]
Fixed in v3.0.2

**Comment by gcacars** [comment]
Not fixed. How I can import this module? I can figure out.

```
import { JWKS } from 'jose';
import generateSecret from 'jose/util/generate_secret';
```

**Unable to resolve path to module...**

@panva We could also have an example with how generate HS256 in keysets? [like this](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#jwks)
I trying this (but module doesn't load... :/
`keystore.add(await generateSecret('HS256'));`

**Comment by panva** [comment]
@gcacars you're mixing up two different major versions. Please refer to the specific version's documentation you want to use. I'm locking this.
