### ISSUE TITLE
improper use of process.getBuiltinModule in Edge Runtime / Next.js middleware

### ISSUE THREAD

**Issue by RMNCLDYO** [panva/jose#752]
> [!IMPORTANT]
> Fixed in https://github.com/panva/jose/releases/tag/v6.0.4
>
> If you encounter any other unexpected issues with v6.x after an upgrade to https://github.com/panva/jose/releases/tag/v6.0.4 please open a separate issue and roll back to v5.x in the meantime.
> 
> I will leave this one open for a while for people to be able to discover that there's a fix and hopefully avoid duplicate issues.

---

### What happened?

When upgrading from `jose` v5.10.0 to v6.0.3 in a Next.js application using Edge Runtime (middleware), the application fails with the error:
```
⨯ Error: A Node.js API is used (process.getBuiltinModule) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
```

Expected behavior: The package should work in Edge Runtime environments as it did in v5.10.0, allowing for JWT operations in Next.js middleware.

Current behavior: The package fails to load due to attempting to use Node.js specific APIs that aren't available in Edge Runtime environments. This is a regression from v5.10.0 where the package worked correctly.

### Version

v6.0.3

### Runtime

Node.js

### Runtime Details

- Node.js: v23.6.0 - Next.js: 15.2.0-canary.33 - OS: macOS - Environment: Edge Runtime in Next.js middleware - Previous working version: jose v5.10.0

### Code to reproduce

```js
The issue can be reproduced using [Vercel's NextJS Saas Starter Kit](https://github.com/nextjs/saas-starter) by upgrading the jose package from v5.10.0 to v6.0.3. The Edge Runtime error will occur immediately after the upgrade.

Alternatively, here's a minimal reproduction case:

// middleware.ts
import { SignJWT, jwtVerify } from 'jose';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export async function middleware(request: NextRequest) {
  // Example JWT operations
  const key = new TextEncoder().encode(process.env.AUTH_SECRET);
  
  try {
    const token = await new SignJWT({ data: 'test' })
      .setProtectedHeader({ alg: 'HS256' })
      .setIssuedAt()
      .setExpirationTime('1d')
      .sign(key);
  } catch (error) {
    console.error(error);
  }
}

export const config = {
  matcher: '/api/:path*',
}
```

### Required

- [x] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
That's funny, because in CI https://github.com/vercel/edge-runtime happily runs the entire test suite with this code in it

```js
globalThis.process?.getBuiltinModule?.("node:buffer")?.Buffer
```

So I'm not sure where this should go, edge-runtime?, turborepo?, or next? Help me out here. The code is safe to execute and the error you're seeing is some overly eager catch that shouldn't be there for this syntax.

**Comment by RMNCLDYO** [comment]
Hmmm, thanks for looking into this! Without Turbopack we get a detailed stack trace showing where the Node.js API is being used:
```
Error: A Node.js API is used (process.getBuiltinModule) which is not supported in the Edge Runtime.
at node_modules/.pnpm/jose@6.0.3/node_modules/jose/dist/webapi/lib/buffer_utils.js
```
The error propagates through this chain:
1. buffer_utils.js (where process.getBuiltinModule is called)
2. base64url.js
3. flattened/sign.js
4. compact/sign.js
5. jwt/sign.js
6. Finally reaching our session.ts

With Turbopack, the error is caught earlier during static analysis:
```
Error: A Node.js API is used (process.getBuiltinModule) which is not supported in the Edge Runtime.
at lib/auth/session.ts:2:0
```

So it seems as though the issue exists regardless of build tool (Turbopack/webpack). Also that the Node.js API usage is in the packages buffer utilities, not just at the top level. The error occurs at both build-time and runtime

Would it be possible to, make `buffer_utils.js` use a pure WebAPI implementation when in Edge Runtime? Or add a build flag to force WebAPI implementation? Or Create an Edge Runtime-specific entry point that avoids Node.js APIs entirely?

Just throwing out a few ideas. Thanks again!

**Comment by miguelski** [comment]
same issue in next.js i was using version 5 without issues in next 15 i tried to upgrade to version 6 today and i got the same error when running locally

`
Error: A Node.js API is used (process.getBuiltinModule) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
`

**Comment by panva** [comment]
Again, the code runs just fine in edge-runtime. I've traced the full trace (even what next considers irrelevant) and the error comes from next's injected polyfills. It's not code analysis, it's actual code getters and function implementations that throw this.

I'm making some changes to call these methods more safely.

There are three occurences

- buffer - base64 encoding/decoding
  - I'm just going to forego the buffer optimalization entirely since https://github.com/tc39/proposal-arraybuffer-base64 is coming hopefully soon, i can actually put that in already.
- crypto - X509 Certificate parsing
  - not sure what to do about this one just yet, it's a good optimization to have when available
- crypto - buffer timing safe equal comparison
  - I'll either keep the JS implementation or replace it with a double hmac method

I should have a fix in a couple hours.

**Comment by RMNCLDYO** [comment]
Great, happy to contribute wherever I can.

Thanks @panva !

**Comment by panva** [comment]
> Running into this with Netlify functions that use SignJWT.
> 
> Throws ReferenceError because webapi looks for crypt.
> 
> Thanks for the prompt attention.

I would like a stack trace from you because netlify is a different runtime than we're dealing with here. Ideally in a separate issue.

**Comment by panva** [comment]
Fixed in https://github.com/panva/jose/releases/tag/v6.0.4

If you see encounter any other unexpected issues with v6.x after an upgrade to https://github.com/panva/jose/releases/tag/v6.0.4 please open a separate issue.

I will leave this one open for a while for people to be able to discover that there's a fix.

**Comment by panva** [comment]
@RMNCLDYO thank you for your report and patience. I apologize for the mishap, these are simply sideeffects of a new major version that was released today with refactored internals (same code for every runtime).

**Comment by oceanicsdotio** [comment]
@panva It is NextJS, but I will try with the update and report if it still happens.

**Comment by panva** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/panva?size=32">@panva](https://github.com/panva) It is NextJS, but I will try with the update and report if it still happens.

Seeing how the particular error is [constructed directly in Next.js](https://github.com/vercel/next.js/blob/eb883cdcfb22517e4babec6f38d3fe86961e2811/packages/next/src/server/web/sandbox/context.ts#L130) I'd say it is 100% fixed in v6.0.4

**Comment by RMNCLDYO** [comment]
> [@RMNCLDYO](https://github.com/RMNCLDYO) thank you for your report and patience. I apologize for the mishap, these are simply sideeffects of a new major version that was released today with refactored internals (same code for every runtime).

I can confirm that the bug was fixed in `v6.0.4` [#753] and is working with and without `turbopack` in `v6.0.5` [#755].

Thanks again for the swift fix @panva!

**Comment by oceanicsdotio** [comment]
> > [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/panva?size=32">@panva](https://github.com/panva) It is NextJS, but I will try with the update and report if it still happens.
> 
> Seeing how the particular error is [constructed directly in Next.js](https://github.com/vercel/next.js/blob/eb883cdcfb22517e4babec6f38d3fe86961e2811/packages/next/src/server/web/sandbox/context.ts#L130) I'd say it is 100% fixed in v6.0.4

I apologize for the bad intel. This particular function is not built by Next, and the issue persists for me. Opened up a new issue as it is unrelated.
